name: mdk_on_air
description: "Wide on-air display"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
build-name: Pilot

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  ### Network
  mqtt_client: ^10.5.1
  osc:
    git:
      url: https://github.com/poeticDev/osc.git
      ref: master
  network_info_plus: ^6.1.1
  dart_ping: ^9.0.1
  uuid: ^4.5.1
  ### State Managing
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  ### data tools
  get_it: ^8.0.2
  drift: ^2.21.0
  drift_flutter: ^0.2.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4

  ### device settings
  kiosk_mode: ^0.7.0
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.21.2
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - asset/img/
#    - asset/img/svg/
#    - asset/env/

  fonts:
    - family: Paperlogy
      fonts:
        - asset: asset/fonts/paperlogy/Paperlogy-9Black.ttf
          weight: 900
        - asset: asset/fonts/paperlogy/Paperlogy-8ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/paperlogy/Paperlogy-7Bold.ttf
          weight: 700
        - asset: asset/fonts/paperlogy/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: asset/fonts/paperlogy/Paperlogy-5Medium.ttf
          weight: 500
        - asset: asset/fonts/paperlogy/Paperlogy-4Regular.ttf
          weight: 400
        - asset: asset/fonts/paperlogy/Paperlogy-3Light.ttf
          weight: 300
        - asset: asset/fonts/paperlogy/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/paperlogy/paperlogy-1Thin.ttf
          weight: 100